"""empty message

Revision ID: 1a9f293f4433
Revises: 83d959398dda
Create Date: 2018-11-11 13:28:56.666707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a9f293f4433'
down_revision = '83d959398dda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'created_at')
    # ### end Alembic commands ###
