"""empty message

Revision ID: 75e6cdb84ee0
Revises: 0d2297e8d4f8
Create Date: 2018-11-07 09:53:30.458316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75e6cdb84ee0'
down_revision = '0d2297e8d4f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('post', sa.Column('slug_title', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'post', ['slug_title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='unique')
    op.drop_column('post', 'slug_title')
    op.drop_table('category')
    # ### end Alembic commands ###
