"""empty message

Revision ID: 83d959398dda
Revises: 0d2297e8d4f8
Create Date: 2018-11-11 11:15:59.453857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83d959398dda'
down_revision = '0d2297e8d4f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug_name')
    )
    op.add_column('post', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('slug_title', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'post', ['slug_title'])
    op.create_foreign_key(None, 'post', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='unique')
    op.drop_column('post', 'slug_title')
    op.drop_column('post', 'category_id')
    op.drop_table('category')
    # ### end Alembic commands ###
